--CONVERT

SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,100) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,101) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,102) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,103) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,104) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,105) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,106) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,107) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,108) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,109) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,110) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,111) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,112) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]
SELECT TOP 1 CONVERT(VARCHAR,[OrderDate] ,113) AS oRDERdATE_ST FROM [dbo].[FactResellerSales]

--TRY CONVERT
SELECT TRY_CONVERT(VARCHAR,GETDATE(),103) AS TODAT_DATE
SELECT TRY_CONVERT(DECIMAL(10,2),'12345') AS NUMBER
SELECT TOP 5 TRY_CONVERT(VARCHAR, [OrderDateKey] ,101) FROM [dbo].[FactResellerSales]
--TRY CONVERT WRONG CONVERTIONS
SELECT TRY_CONVERT(INT,NULL)
SELECT TRY_CONVERT(INT,'KANISHKA')
SELECT TRY_CONVERT(DATETIME, '23/08/1996')

--PARSE FUNCTION
--SQL PARSE function to convert the string data to either Date time, or Number type
SELECT PARSE('1234' AS DECIMAL(10,2)) AS NUMBER
SELECT PARSE('23/08/1996' AS DATETIME2) AS NUMBER
-- SQL PARSE FUNCTION Example 
DECLARE @str AS VARCHAR(50)
SET @str = '11122'

SELECT PARSE(@str AS INT) AS Result; 

-- Direct Inputs
SELECT PARSE('1234' AS DECIMAL(10, 2)) AS Result; 
 
SELECT PARSE('06/03/2017' AS DATETIME) AS Result;  

SELECT PARSE('06/03/2017' AS DATETIME2) AS Result;
-- SQL PARSE FUNCTION Example 
DECLARE @strval AS VARCHAR(50)
SET @strval = NULL

SELECT PARSE(@strval AS INT) AS Result;

-- SQL TRY_PARSE FUNCTION Example 
DECLARE @str AS VARCHAR(50)
SET @str = '1234'

SELECT TRY_PARSE(@str AS INT) AS Result; 

-- Direct Inputs
SELECT TRY_PARSE('4455' AS DECIMAL(10, 2)) AS Result; 
 
SELECT TRY_PARSE('03/03/2017' AS DATETIME) AS Result;  

SELECT TRY_PARSE('03/03/2017' AS DATETIME2) AS Result; 

SELECT TRY_PARSE('Tutorial Gateway' AS DATETIME USING 'en-US') AS Result;


--IIF FUNCTION WITH TRY_PARSE
SELECT IIF(
	    TRY_PARSE('KANISHKA' AS DATETIME) IS NULL, 
		       GETDATE(), 
		       'False'
	   ) AS Result;
